Feature/hh26
Muniox/megak-v2-head-hunter-gr9-frontend pull request #4
Opened 2023-04-19 20:50 UTC by MaJan433

2023-04-20 14:42 UTC, Muniox approved these changes
Kod jest dobrze sformatowany, są opisane Propsy. Na pewno przy integracji będą jeszcze zmiany, ale to zostawiamy na później, Nie mam do czego się przyczepić :)
Approved.

2023-04-21 06:00 UTC, Przekol requested changes

2023-04-21 06:00 UTC, Przekol commented on src/components/RegistrationResultPage.tsx
> +          <h1 className="text-white text-5xl font-bold mb-10">Thank you for registration</h1>
Nie mieliśmy tego jednak po polsku pisać?

2023-04-21 14:01 UTC, MaJan433 commented on src/components/RegistrationResultPage.tsx
> +          <h1 className="text-white text-5xl font-bold mb-10">Thank you for registration</h1>
Już to poprawiam

2023-04-23 09:45 UTC, Przekol commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FE] Stworzenie widoku typu "dziękujemy za rejestracje" oraz widoku błędu](https://trello.com/c/eKoNsFuJ/26-fe-stworzenie-widoku-typu-dzi%C4%99kujemy-za-rejestracje-oraz-widoku-b%C5%82%C4%99du)

2023-04-23 18:16 UTC, Przekol approved these changes

2023-04-25 04:46 UTC, merged